<template>
<div>
  <b-carousel
    id="carousel-fade"
    style="text-shadow: 0px 0px 2px #000"
    fade
    indicators
    img-width="1024"
    img-height="480"
  >
    <b-carousel-slide
      caption="Lleida" 
      img-src="../assets/lleida.jpg"
    ></b-carousel-slide>
    <b-carousel-slide
      caption="Tarragona"
      img-src="../assets/tarragona.jpg"
    ></b-carousel-slide>
    <b-carousel-slide
      caption="Barcelona"
      img-src="../assets/barcelona.jpg"
    ></b-carousel-slide>
    <b-carousel-slide
      caption="Girona"
      img-src="../assets/girona.jpg"
    ></b-carousel-slide>
  </b-carousel>
</div>
</template>